---
name: build

description: "ビルドするActions"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: electronuserland/builder:wine
    timeout-minutes: 20
    steps:
      - uses: 'actions/checkout@v3'
      - uses: './.github/actions/install-npm-packages'
