---
name: GitHub Script Message

on:
  push:
    branches:
      - main

jobs:
  composite_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test

  github-script-message:
    needs: [composite_test]
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: message
      uses: actions/github-script@v6
      id: set-result
      with:
        script: return "main ブランチにマージされた の Actions"
        result-encoding: string

  hello_world_job:
    needs: [composite_test]
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Random Number
        id: random-number
        uses: ./.github/actions/random-number
        with:
          who-to-greet: 'Mona the Octocat'

      - name: echo Random Number
        run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
