---
name: GitHub Script Message

on:
  push:
    branches:
      - main

jobs:
  composite_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test

  github-script-message:
    needs: [composite_test]
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: message
      uses: actions/github-script@v6
      id: set-result
      with:
        script: return "main ブランチにマージされた の Actions"
        result-encoding: string
